### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'change_column_value' of undefined

### ISSUE THREAD

**Issue by budparr** [willstenzel/update-monday-status-action#3]
Hi @willstenzel Thanks very much for putting this together. I dropped this into a repo today and am getting this error. As far as I can tell I have all my values input correctly. Any ideas?

```
 with:
    API_TOKEN: ***
    BOARD_ID: 1067034989
    COLUMN_ID: status
    submitted-status: PR Submitted
    merged-status: closed
    pull-request-body: https://myurl.monday.com/boards/1067034989/pulses/1123743630
    merged: true
(node:2390) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'change_column_value' of undefined
    at /home/runner/work/_actions/willstenzel/update-monday-status-action/v1.0/dist/index.js:5914:40
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2390) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2390) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by willstenzel** [comment]
Hi @budparr thanks for submitting an issue. I'm sorry that the GitHub action is not currently working for you. 

Not sure exactly what the issue is, the only thing I can think of is double checking that the names of the `submitted-status` and `merged-status` are correct. I see that the `submitted-status` uses upper case "PR Submitted" where as the `merged-status` uses lower case "closed".

**Comment by budparr** [comment]
Yeah, tried all that and it still fails. No worries. I'll go through and figure it out.
